/*C343 / Summer 2022
2022-5-12
Haochen Sun
haocsun*/
public class Tweet {
    private String tweet;
    private String author;

    public Tweet(String tweet, String author){
        this.author = author;
        this.tweet = tweet;
    }
    public String getTweet(){
        return tweet;
    }

    public String getAuthor(){
        return author;
    }

    public void printTweet(){
        System.out.println(tweet);
    }

    public boolean contains(String str){
        return(tweet.contains(str));
    }

    public String toString(){
        return tweet + " " + author + "\n";
    }

    public static void main(String[] args) {
        Tweet twt = new Tweet("It is quite easy to learn about a person's mobility preferences from data generated by their phone" , "someperson");
        twt.printTweet();
        System.out.println(twt.contains("easy"));
        System.out.println(twt.contains("fun"));



    }
}
